In [1]:
import numpy as np
import pandas as pd
import sqlite3

In [5]:
print("=== TASK 1: Database Creation ===")

=== TASK 1: Database Creation ===

In [2]:
conn = sqlite3.connect("bookstore.db")

In [3]:
cursor = conn.cursor()

In [7]:
cursor.execute("""
CREATE TABLE IF NOT EXIsts Books(
    book_id INTEGER Primary Key Autoincrement,
    title text Not Null,
    author text Not Null,
    price REAL Not Null,
    stock_quantity INTEGER Default 0
)
""")
print("Books table created successfully")

Books table created successfully

In [8]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS CUSTOMERS(
    customer_id INTEGER Primary Key Autoincrement,
    name TEXT Not Null,
    email TEXT Unique Not Null,
    city TEXT,
    join_date TEXT
    )
""")
print("Customers table created successfully")

Customers table created successfully

In [9]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders(
    order_id INTEGER Primary Key Autoincrement,
    customer_id INTEGER ForeignKey referencing Customers,
    book_id INTEGER ForeignKey referencing Books,
    quantity INTEGER Not Null,
    order_date TEXT Not Null,
    total_amount REAL
)                    
""")
print("Orders table created successfully")

Orders table created successfully

In [10]:
print("Schema for books table:")

Schema for books table:

In [11]:
cursor.execute("PRAGMA table_info(Books)")
schema = cursor.fetchall()

for column in schema:
    print(column)

(0, 'book_id', 'INTEGER', 0, None, 1)
(1, 'title', 'TEXT', 1, None, 0)
(2, 'author', 'TEXT', 1, None, 0)
(3, 'price', 'REAL', 1, None, 0)
(4, 'stock_quantity', 'INTEGER', 0, '0', 0)

In [12]:
cursor.execute("PRAGMA table_info(CUSTOMERS)")
schema = cursor.fetchall()

for column in schema:
    print(column)

(0, 'customer_id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'email', 'TEXT', 1, None, 0)
(3, 'city', 'TEXT', 0, None, 0)
(4, 'join_date', 'TEXT', 0, None, 0)

In [13]:
cursor.execute("PRAGMA table_info(orders)")
schema = cursor.fetchall()

for column in schema:
    print(column)

(0, 'order_id', 'INTEGER', 0, None, 1)
(1, 'customer_id', 'INTEGER ForeignKey referencing Customers', 0, None, 0)
(2, 'book_id', 'INTEGER ForeignKey referencing Books', 0, None, 0)
(3, 'quantity', 'INTEGER', 1, None, 0)
(4, 'order_date', 'TEXT', 1, None, 0)
(5, 'total_amount', 'REAL', 0, None, 0)

In [14]:
books = [
    ('Python Programming', 'John Smith', 599.99, 25),
    ('Data Science Handbook', 'Jane Doe', 899.50, 15),
    ('Machine Learning Basics', 'Alan Turing', 1299.00, 10),
    ('SQL Essentials', 'Edgar Codd', 499.99, 30),
    ('Web Development', 'Tim Berners', 799.00, 20)
]

cursor.executemany("""
INSERT INTO BOOKS (title, author, price, stock_quantity)
VALUES (?, ?, ?, ?)
""", books)

conn.commit()

In [15]:
CUSTOMERS = [
    ('Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15'),
    ('Priya Patel', 'priya@email.com', 'Delhi', '2024-01-20'),
    ('Amit Kumar', 'amit@email.com', 'Bangalore', '2024-02-01'),
    ('Sneha Reddy', 'sneha@email.com', 'Hyderabad', '2024-02-10'),
    ('Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')
]
cursor.executemany("""
INSERT OR IGNORE INTO CUSTOMERS(name,email,city,join_date)
VALUES (?, ?, ?, ?)
""", CUSTOMERS)

conn.commit()

In [16]:
orders = [
    (1, 1, 2, '2024-03-01', 1199.00),
    (1, 2, 1, '2024-03-02', 899.50),
    (2, 1, 1, '2024-03-03', 599.99),
    (2, 3, 1, '2024-03-05', 1299.00),
    (3, 4, 3, '2024-03-07', 1499.97),
    (4, 2, 1, '2024-03-10', 899.50),
    (5, 5, 2, '2024-03-12', 1598.00)
]


cursor.executemany("""
INSERT INTO orders(customer_id,book_id,quantity,order_date,total_amount)
VALUES (?, ?, ?, ?, ?)
""",orders)

conn.commit()

In [35]:
cursor.execute("""
SELECT customer_id,name,email,city FROM Customers
WHERE city = 'Mumbai'
""")
schema = cursor.fetchall()
for i in schema:
    print(i)

(1, 'Rahul Sharma', 'rahul@email.com', 'Mumbai')
(5, 'Vikram Singh', 'vikram@email.com', 'Mumbai')

In [37]:
cursor.execute("""
SELECT book_id,title,price,stock_quantity from books
WHERE price > 800 and stock_quantity >= 10
""")
schema = cursor.fetchall()
for i in schema:
    print(i)

(2, 'Data Science Handbook', 899.5, 15)
(3, 'Machine Learning Basics', 1299.0, 10)
(7, 'Data Science Handbook', 899.5, 15)
(8, 'Machine Learning Basics', 1299.0, 10)

In [38]:
cursor.execute("""
select count(order_id)
from orders
""")
schema = cursor.fetchall()
for i in schema:
    print(i)

(14,)

In [32]:
cursor.execute("""select * from orders
group by quantity
order by quantity desc
""")
schema = cursor.fetchall()
for i in schema:
    print(i)

(5, 3, 4, 3, '2024-03-07', 1499.97)
(1, 1, 1, 2, '2024-03-01', 1199.0)
(2, 1, 2, 1, '2024-03-02', 899.5)

In [9]:
cursor.execute("""
select sum(total_amount) from orders
""")
schema = cursor.fetchone()
for i in schema:
    print(i)

15989.919999999998

In [10]:
df_customers = pd.read_sql("SELECT * FROM customers", conn)
df_customers

   customer_id          name             email       city   join_date
0            1  Rahul Sharma   rahul@email.com     Mumbai  2024-01-15
1            2   Priya Patel   priya@email.com      Delhi  2024-01-20
2            3    Amit Kumar    amit@email.com  Bangalore  2024-02-01
3            4   Sneha Reddy   sneha@email.com  Hyderabad  2024-02-10
4            5  Vikram Singh  vikram@email.com     Mumbai  2024-02-15

In [11]:
df_books = pd.read_sql("SELECT * FROM books", conn)
df_books

   book_id                    title       author    price  stock_quantity
0        1       Python Programming   John Smith   599.99              25
1        2    Data Science Handbook     Jane Doe   899.50              15
2        3  Machine Learning Basics  Alan Turing  1299.00              10
3        4           SQL Essentials   Edgar Codd   499.99              30
4        5          Web Development  Tim Berners   799.00              20
5        6       Python Programming   John Smith   599.99              25
6        7    Data Science Handbook     Jane Doe   899.50              15
7        8  Machine Learning Basics  Alan Turing  1299.00              10
8        9           SQL Essentials   Edgar Codd   499.99              30
9       10          Web Development  Tim Berners   799.00              20

In [12]:
df_orders = pd.read_sql("SELECT * from orders",conn)
df_orders

    order_id  customer_id  book_id  quantity  order_date  total_amount
0          1            1        1         2  2024-03-01       1199.00
1          2            1        2         1  2024-03-02        899.50
2          3            2        1         1  2024-03-03        599.99
3          4            2        3         1  2024-03-05       1299.00
4          5            3        4         3  2024-03-07       1499.97
5          6            4        2         1  2024-03-10        899.50
6          7            5        5         2  2024-03-12       1598.00
7          8            1        1         2  2024-03-01       1199.00
8          9            1        2         1  2024-03-02        899.50
9         10            2        1         1  2024-03-03        599.99
10        11            2        3         1  2024-03-05       1299.00
11        12            3        4         3  2024-03-07       1499.97
12        13            4        2         1  2024-03-10        899.50
13        14            5        5         2  2024-03-12       1598.00

In [13]:
df_customers.head()

   customer_id          name             email       city   join_date
0            1  Rahul Sharma   rahul@email.com     Mumbai  2024-01-15
1            2   Priya Patel   priya@email.com      Delhi  2024-01-20
2            3    Amit Kumar    amit@email.com  Bangalore  2024-02-01
3            4   Sneha Reddy   sneha@email.com  Hyderabad  2024-02-10
4            5  Vikram Singh  vikram@email.com     Mumbai  2024-02-15

In [14]:
df_orders.head()

   order_id  customer_id  book_id  quantity  order_date  total_amount
0         1            1        1         2  2024-03-01       1199.00
1         2            1        2         1  2024-03-02        899.50
2         3            2        1         1  2024-03-03        599.99
3         4            2        3         1  2024-03-05       1299.00
4         5            3        4         3  2024-03-07       1499.97

In [15]:
df_books.head()

   book_id                    title       author    price  stock_quantity
0        1       Python Programming   John Smith   599.99              25
1        2    Data Science Handbook     Jane Doe   899.50              15
2        3  Machine Learning Basics  Alan Turing  1299.00              10
3        4           SQL Essentials   Edgar Codd   499.99              30
4        5          Web Development  Tim Berners   799.00              20

In [24]:
df_orders.merge(df_customers)

,order_id,customer_id,book_id,quantity,order_date,total_amount,name,email,city,join_date
0,1,1,1,2,2024-03-01,1199.00,Rahul Sharma,rahul@email.com,Mumbai,2024-01-15
1,2,1,2,1,2024-03-02,899.50,Rahul Sharma,rahul@email.com,Mumbai,2024-01-15
2,8,1,1,2,2024-03-01,1199.00,Rahul Sharma,rahul@email.com,Mumbai,2024-01-15
3,9,1,2,1,2024-03-02,899.50,Rahul Sharma,rahul@email.com,Mumbai,2024-01-15
4,3,2,1,1,2024-03-03,599.99,Priya Patel,priya@email.com,Delhi,2024-01-20
5,4,2,3,1,2024-03-05,1299.00,Priya Patel,priya@email.com,Delhi,2024-01-20
6,10,2,1,1,2024-03-03,599.99,Priya Patel,priya@email.com,Delhi,2024-01-20
7,11,2,3,1,2024-03-05,1299.00,Priya Patel,priya@email.com,Delhi,2024-01-20
8,5,3,4,3,2024-03-07,1499.97,Amit Kumar,amit@email.com,Bangalore,2024-02-01
9,12,3,4,3,2024-03-07,1499.97,Amit Kumar,amit@email.com,Bangalore,2024-02-01
10,6,4,2,1,2024-03-10,899.50,Sneha Reddy,sneha@email.com,Hyderabad,2024-02-10
11,13,4,2,1,2024-03-10,899.50,Sneha Reddy,sneha@email.com,Hyderabad,2024-02-10
12,7,5,5,2,2024-03-12,1598.00,Vikram Singh,vikram@email.com,Mumbai,2024-02-15
13,14,5,5,2,2024-03-12,1598.00,Vikram Singh,vikram@email.com,Mumbai,2024-02-15